# Generated by Django 4.2.10 on 2024-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=3000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
